### ISSUE TITLE
Issue with @keyframes

### ISSUE THREAD

**Issue by teddywsi** [ymrdf/postcss-plugin-namespace#1]
It appears that this plugin adds the namespace inside of `@keyframes {}` declarations, in front of each keyframe (e.g., `from`, `to`, `50%`, etc.). This invalidates the keyframes animation.

Example output:
```css
@keyframes pulse {
  .namespace 0% {
    transform: scaleX(1);
  }

  .namespace 50% {
    transform: scale3d(1.05, 1.05, 1.05);
  }

  .namespace to {
    transform: scaleX(1);
  }
}
```
